language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t bearshadow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bearshadow/docker-react npm run test -- --watchAll=false